### ISSUE TITLE
The plugin 'VBANDeck' crashed with code 1:-2147450740

### ISSUE THREAD

**Issue by mipsou** [burdoto/VBAN-StreamDeck-Plugin#12]
0:51:02.801                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_98961b8ad78863a54a818ca5e28f2dfe>::operator ()(): The plugin 'VBANDeck' crashed with code 1:-2147450740
20:51:02.801                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_98961b8ad78863a54a818ca5e28f2dfe>::operator ()(): Restarting plugin 'VBANDeck'
20:51:02.839                     StreamDeck                        ESDCustomPlugin::StartPlugin::<lambda_98961b8ad78863a54a818ca5e28f2dfe>::operator ()(): The plugin 'VBANDeck' crashed with code 1:-2147450740

**Comment by mipsou** [comment]
a simple Source Script same as manual vban:
`BEGIN_SECTION("vban1")`
`Strip(0).Mute=1;`
`END_SECTION`

**Comment by burdoto** [comment]
Hello @mips81,
Have you tried using [this prerelease](https://github.com/burdoto/VBANDeck/tree/1.0.1)?
It includes extra logging and some small fixes.
Please install that version of the plugin and if the issue persists, please share the Log file available at ``%appdata%\Elgato\StreamDeck\Plugins\de.kaleidox.vbandeck.sdPlugin\pluginlog.log`.
Please note that this log file could only be available after the update.
Thanks!

**Comment by burdoto** [comment]
Hello! Since I've not heard back from you in quite a while, I'll see this Issue as fixed. Feel free to comment and I'll reopen it again :)

**Comment by mipsou** [comment]
This problem was not resolved with any version.

**Comment by burdoto** [comment]
Could you please provide the log files, as described [here](https://github.com/burdoto/VBANDeck/issues/12#issuecomment-561099986)?

**Comment by mipsou** [comment]
No log file in this place

**Comment by mipsou** [comment]
New place for all logs —» %AppData%\Roaming\Elgato\StreamDeck\logs

[StreamDeck.logs.zip](https://github.com/burdoto/VBANDeck/files/4837276/StreamDeck.logs.zip)

**Comment by burdoto** [comment]
I'm sorry, I should have added that you should use the version that I linked for generating Log Files. Have you done that? I'm missing some of the log output I was expecting 🤔

**Comment by mipsou** [comment]
Yes, i use your last version and the latest streamdeck.exe .
Do you need dump StreamDeck.exe.5336.dmp ?

**Comment by Phat32** [comment]
I am also having this issue and have installed the pre-release version of the plugin. The log file as described above is not generating. The only information I can get is from the StreamDeck0.log file in %appdata%\Elgato\StreamDeck\Logs

I will be very happy to provide the log files if possible and get this issue sorted :)

**Comment by burdoto** [comment]
Hello, a new version of VBANDeck has been released, v1.0.2
Please download that and check if your issue still persists.
