### ISSUE TITLE
Añadido de puerto serie

### ISSUE THREAD

**Issue by GHprograms** [burdoto/VBAN-StreamDeck-Plugin#14]
Añadir la misma funcion pero por puerto serie para sistemas de control que funcionan via usb convertido a serial. Como por ejemplo un arduino que controla, luces, i otros dispositivos. Arduino es modular de forma que se puede insertar, infrarrojos bluetooth, etc ...

**Comment by burdoto** [comment]
Please stick to posting in English.

**Comment by burdoto** [comment]
Hello, for implementing the VBAN Protocol on an Arduino, this is the wrong Project; you might be better off looking at [the Vban Protocol implementation](https://github.com/comroid-git/VBAN-API-CS) created for this plugin.
