### ISSUE TITLE
Script can't be save on streamdeck

### ISSUE THREAD

**Issue by Neoakira** [burdoto/VBAN-StreamDeck-Plugin#2]
Hi,
I compile the project for testing but there is an issue with "enter VoiceMeeter Remote Script" on the StreamDeck,
When i writte the script, the plugin don't save the text.

**Comment by burdoto** [comment]
Hello Neoakira;
VBANDeck development is currently paused. The plugin currently is not in a reachable state yet, but it will become finished at some point.
As soon as this point is reached, I will talk to you back in this issue.

**Comment by burdoto** [comment]
VBANDeck has been released at version 1.0.0, and is working, so I'm closing this issue.
