### ISSUE TITLE
Add usage examples to README

### ISSUE THREAD

**Issue by DjSni** [burdoto/VBAN-StreamDeck-Plugin#5]
Hallo,

it might be cool if you added a README with some configurations examples. 

Regards

**Comment by mipsou** [comment]
Did you use this ?

`SendText("vban1",Strip(0).Mute=1;);`

**Comment by Save5Bucks** [comment]
I am trying to understand how to use this on my Stream Deck. I have a 2 PC setup and can not get any of the API functions/scriptlets to work. In SendText("vban1",Strip(0).Mute=1;); what is vban1 referring to?, or is this just the API name for VBAN?

**Comment by endcode-net** [comment]
I realize this is a few years later. not sure where this is going south. there seems to be no transport between the plugin and Voice Meter. i have installed the 1.0.1 version. and still nothing. even went as far as installing Voice Meter on the same system as the Stream Deck to rule out a Firewall issue.

**Comment by burdoto** [comment]
Hello, I'm deeply sorry for the hell late response.

I've just FINALLY added [some usage examples](https://github.com/burdoto/VBANDeck#readme).
As noted in this readme, please refer to [this Document, chapter "MACRO Buttons > VoiceMeeter Remote Requests"](https://vb-audio.com/Voicemeeter/VoicemeeterBanana_UserManual.pdf) for information about scripting.

When looking into this I noticed that the plugin is completely out of date and broken as of Version 1.0.1, however I released a new [Version, 1.0.2](https://github.com/burdoto/VBANDeck/releases/tag/1.0.2).

Again, my honest apologies for not getting rid of this issue earlier.
